const mockUpcomingEvents = [
  {
    id: 1,
    icon: "🤖",
    title: "AI Workshop Series ⭐",
    department: "CS",
    departmentTagClass: "tag-cs",
    subtitle: "Introduction to Machine Learning fundamentals",
    date: "2025-06-25",
    time: "2:00 PM",
    location: "Lab 301",
    registered: "45/50",
    description: "Introduction to Machine Learning fundamentals",
    actions: [
      { label: "View Details", link: "", class: "btn-secondary" },
      { label: "Register", link: "", class: "btn-primary" },
    ],
  },
  {
    id: 2,
    icon: "🏗️",
    title: "Software Architecture Seminar",
    department: "SE",
    departmentTagClass: "tag-se",
    subtitle: "Best practices in modern software architecture",
    date: "2025-06-28",
    time: "10:00 AM",
    location: "Auditorium A",
    registered: "32/100",
    description: "Best practices in modern software architecture",
    actions: [
      { label: "View Details", link: "", class: "btn-secondary" },
      { label: "Register", link: "", class: "btn-primary" },
    ],
  },
  {
    id: 3,
    icon: "🗃️",
    title: "Database Design Competition 🏆",
    department: "IS",
    departmentTagClass: "tag-is",
    subtitle: "Annual database design challenge",
    date: "2025-07-02",
    time: "9:00 AM",
    location: "Computer Lab 2",
    registered: "28/30",
    description: "Annual database design challenge",
    actions: [
      { label: "View Details", link: "", class: "btn-secondary" },
      { label: "Register", link: "", class: "btn-primary" },
    ],
  },
];
